server:
  port: 8082

spring:
  mongodb:
    uri: mongodb://mongoadmin:mongoadmin@localhost:27017/
    database: fitnessactivity
  rabbitmq:
    template:
      exchange: fitness.exchange
      default-receive-queue: activity.queue
      routing-key: activity.tracking
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

